site_name: AGU 2018 ARD & Planet Platform
site_description: Analysis-Ready Data and Sensor Fusion with the Planet Platform
site_author: Samapriya Roy
site_url: https://samapriya.github.io/projects/open-impact/
theme: 'material'
# Repository
repo_name: AGU 2018
repo_url: https://github.com/samapriya/Open-Impact/tree/master/docs/agu2018

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 Samapriya Roy'

extra:
  social:
    - type: github-alt
      link: https://github.com/samapriya
    - type: medium
      link: https://medium.com/@samapriyaroy
    - type: twitter
      link: https://twitter.com/samapriyaroy
    - type: linkedin
      link: https://www.linkedin.com/in/samapriya

# Configuration
theme:
  name: material
  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  use_directory_urls: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  palette:
    primary: amber
    accent: indigo

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - AGU 2018 Scientific Workshop: index.md
  - Register and Setup: prerequisite.md
  - Getting Started:
    - Setting up your Accounts: projects/setup.md
    - Basic Housekeeping and Setup: projects/housekeeping.md
  - Image & Image Collections:
    - Planet Imagery: planet-asset.md
    - Images in Earth Engine: projects/images.md
    - Image Collection in Earth Engine: projects/imagecollection.md
  - From Planet to Earth Engine:
    - Downloading Images: projects/downloading-images.md
    - Getting Images into Google Earth Engine: projects/getting-images-ee.md
  # - Functions & Reducers:
  #   - Functions: projects/functions.md
  #   - Reducers and Charts: projects/reducers.md
  # - Building a complete script:
  #   - Monthly Cloud free composites: projects/multimonth.md
  #   - Earth Engine exports: projects/export.md
  # - Analytics in Earth Engine:
  #   - Edge Detection: projects/edges.md
  #   - Skysat Image Classification: projects/classification.md
  # - Extra Addon:
  #   - PlanetScope Explorer & Exporter: projects/explore.md
  - Citations: citations.md
  - Contact Us: contact.md

google_analytics:
  -
  - auto
